In [1]:
# 1.	Write a Python Program to find sum of array?

In [279]:
import numpy as np

In [280]:
arr = np.array([1,2,3,4])

In [281]:
sum(arr)

10

In [282]:
# 2.	Write a Python Program to find largest element in an array?

In [283]:
arr2 = np.asanyarray([[1,2,20,4],[5,6,7,8]])

In [284]:
arr2

array([[ 1,  2, 20,  4],
       [ 5,  6,  7,  8]])

In [285]:
print(f"Largest element in an array \n {arr2}  \n is {arr2.max()} ")

Largest element in an array 
 [[ 1  2 20  4]
 [ 5  6  7  8]]  
 is 20 


In [286]:
# 3.	Write a Python Program for array rotation?

In [287]:
arr3 = np.asarray([[1,2,20,4],[5,6,7,8]])


In [288]:
arr3

array([[ 1,  2, 20,  4],
       [ 5,  6,  7,  8]])

In [289]:
arr3.T

array([[ 1,  5],
       [ 2,  6],
       [20,  7],
       [ 4,  8]])

In [290]:
# 4.	Write a Python Program to Split the array and add the first part to the end?

In [291]:
arr4 = np.asarray([[1,2,20,4],[5,6,7,8]])

In [292]:
art = np.array([1,2,3,4])

In [293]:
import copy
def arrSpliter(arr, postion):
    n = len(arr)
    for i in range(0,postion):
        x = copy.copy(arr[0])
        for j in range(0,n-1):
            arr[j] = arr[j+1]
        arr[n-1] = x
    print(arr)
        
    

In [294]:
print(f'Array before {art}')

Array before [1 2 3 4]


In [295]:
print('Array After is ')
arrSpliter(art,2)

Array After is 
[3 4 1 2]


In [296]:
print(f'Array before {arr4}')

Array before [[ 1  2 20  4]
 [ 5  6  7  8]]


In [297]:
print('Array After is ')
arrSpliter(arr4,1)

Array After is 
[[ 5  6  7  8]
 [ 1  2 20  4]]


In [298]:
# 5.	Write a Python Program to check if given array is Monotonic?
# An array is monotonic if it is either monotone increasing or monotone decreasing.

In [299]:
def monotonicCheck(arr):
    increasing = True
    decreasing = True
    n = len(arr)
    for i in range(0,n-1):
        if arr[i] > arr[i+1]:
            increasing = False
        if arr[i] < arr[i+1]:
            decreasing = False
    if (increasing ==True) or (decreasing==True):
        print(f"{arr} is Monotonic array")
    else:
        print(f"{arr} is Not Monotonic array")
        

In [300]:
testarr = np.array([1,2,2,3]) 

In [301]:
monotonicCheck(testarr)

[1 2 2 3] is Monotonic array


In [302]:
testarr2 = np.array([5,15, 20, 10])

In [303]:
monotonicCheck(testarr2)

[ 5 15 20 10] is Not Monotonic array
